import Head from "next/head";
import Timeline from "@/components/Timeline";
import RegisterForApp from "@/components/registerForApp";


export default function Home() {
  return (
    <>
      <Head>
        <title>SNS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <RegisterForApp />
        <Timeline />
      </div>
    </>
  );
}
